package com.ctrlshift.core.notify;

public enum Group {
    // @formatter:off
    ADZ, APPNEXUS, ADWORDS, DBM, FBM, APPLIFT, TUBEMOGUL, MEDIAMATH, SIZMEK, IPINYOU,
    STATS, MAIN, DEVICE, SOCIAL, VIDEO, DOMAIN, CATEGORY, GEO, BROWSER,
    VALIDATION, EXTRESOURCES, SEGMENT, CONTAINER_TAG, GOOGLEANALYTICS, EXCHANGE, FREQUENCY
    // @formatter:on
}